INSERT INTO public.unit (id,measure_id, name_ru, name_uz) VALUES
 ( gen_random_uuid(), 0, 'другой', 'boshqa'),
 ( gen_random_uuid(), 1, 'штук', 'dona'),
 ( gen_random_uuid(), 2, 'пачка', 'pachka'),
 ( gen_random_uuid(), 3, 'миллиграмм', 'milligramm'),
 ( gen_random_uuid(), 4, 'грамм', 'gramm'),
 ( gen_random_uuid(), 5, 'килограмм', 'kilogramm'),
 ( gen_random_uuid(), 6, 'центнер', 'sentner'),
 ( gen_random_uuid(), 7, 'тонна', 'tonna'),
 ( gen_random_uuid(), 8, 'миллиметр', 'millimetr'),
 ( gen_random_uuid(), 9, 'сантиметр', 'santimetr'),
 ( gen_random_uuid(), 10, 'дециметр', 'detsimetr'),
 ( gen_random_uuid(), 11, 'метр', 'metr'),
 ( gen_random_uuid(), 12, 'километр', 'kilometr'),
 ( gen_random_uuid(), 13, 'кв. миллиметр', 'kv. millimetr'),
 ( gen_random_uuid(), 14, 'кв. сантиметр', 'kv. santimetr'),
 ( gen_random_uuid(), 15, 'кв. дециметр', 'kv. detsimetr'),
 ( gen_random_uuid(), 16, 'кв. метр', 'kv. metr'),
 ( gen_random_uuid(), 17, '1000 куб. метр', '1000 kub. metr'),
 ( gen_random_uuid(), 18, 'кв. километр', 'kv. kilometr'),
 ( gen_random_uuid(), 19, 'куб. дециметр', 'kub. detsimetr'),
 ( gen_random_uuid(), 20, 'куб. метр', 'kub. metr'),
 ( gen_random_uuid(), 21, 'куб. километр', 'kub. kilometr'),
 ( gen_random_uuid(), 22, 'миллилитр', 'millilitr'),
 ( gen_random_uuid(), 23, 'литр', 'litr'),
 ( gen_random_uuid(), 24, 'дал', 'dal'),
 ( gen_random_uuid(), 25, 'сум', 'so‘m'),
 ( gen_random_uuid(), 26, 'комплект', 'to‘plam'),
 ( gen_random_uuid(), 27, 'сутка', 'tunu-kun'),
 ( gen_random_uuid(), 28, 'час', 'soat'),
 ( gen_random_uuid(), 29, 'пар', 'juft'),
 ( gen_random_uuid(), 30, 'флакон', 'flakon'),
 ( gen_random_uuid(), 31, 'размещение', 'turar joy'),
 ( gen_random_uuid(), 32, 'показы', 'показы'),
 ( gen_random_uuid(), 33, 'коробка', 'quti'),
 ( gen_random_uuid(), 34, 'моточас', 'ishvaqti'),
 ( gen_random_uuid(), 35, 'Гкал', 'Gkal'),
 ( gen_random_uuid(), 36, 'кВтч', 'kVts'),
 ( gen_random_uuid(), 37, 'рейс', 'qatnov'),
 ( gen_random_uuid(), 38, 'упаковка', 'qadoq'),
 ( gen_random_uuid(), 39, 'минут', 'daqiqa'),
 ( gen_random_uuid(), 40, 'норма/час', 'norma/soat'),
 ( gen_random_uuid(), 41, 'баллон', 'ballon'),
 ( gen_random_uuid(), 42, 'день', 'kun'),
 ( gen_random_uuid(), 43, 'месяц', 'oy'),
 ( gen_random_uuid(), 44, 'мегабайт', 'megabayt'),
 ( gen_random_uuid(), 45, 'серия', 'seriya'),
 ( gen_random_uuid(), 46, 'бутылка', 'shisha'),
 ( gen_random_uuid(), 47, 'кега', 'кега'),
 ( gen_random_uuid(), 48, 'публикация', 'nashr'),
 ( gen_random_uuid(), 49, 'рулон', 'rulon'),
 ( gen_random_uuid(), 50, 'порция', 'bir qismi'),
 ( gen_random_uuid(), 51, 'погонный метр', 'pogon metr'),
 ( gen_random_uuid(), 52, 'га', 'ga'),
 ( gen_random_uuid(), 53, 'кВарч', 'kVar/s'),
 ( gen_random_uuid(), 54, 'человек/час', 'odam/soat'),
 ( gen_random_uuid(), 55, 'кВар', 'kVar'),
 ( gen_random_uuid(), 56, 'кВт', 'kVt'),
 ( gen_random_uuid(), 57, 'год', 'yil'),
 ( gen_random_uuid(), 58, 'лист', 'varaq'),
 ( gen_random_uuid(), 59, 'блок', 'blok'),
 ( gen_random_uuid(), 60, 'машина/час', 'mashina/soat'),
 ( gen_random_uuid(), 61, 'тонна/километр', 'tonna/kilometr'),
 ( gen_random_uuid(), 62, 'ящик', 'yashik'),
 ( gen_random_uuid(), 63, 'ампула', 'ampula'),
 ( gen_random_uuid(), 64, 'базовая тонна', 'baza tonna'),
 ( gen_random_uuid(), 65, 'банка', 'banka'),
 ( gen_random_uuid(), 66, 'баррель', 'barrel'),
 ( gen_random_uuid(), 67, 'бобина', 'bobina'),
 ( gen_random_uuid(), 68, 'бочка', 'bochka'),
 ( gen_random_uuid(), 69, 'вагон', 'vagon'),
 ( gen_random_uuid(), 70, 'галлон', 'gallon'),
 ( gen_random_uuid(), 71, 'декалитр', 'dekalitr'),
 ( gen_random_uuid(), 72, 'доза', 'doza'),
 ( gen_random_uuid(), 73, 'работа', 'ish'),
 ( gen_random_uuid(), 74, 'канистр', 'kanistr'),
 ( gen_random_uuid(), 75, 'Ккалл', 'Kkal'),
 ( gen_random_uuid(), 76, 'Мешок', 'Meshok'),
 ( gen_random_uuid(), 77, 'млн.т.', 'mln.t.'),
 ( gen_random_uuid(), 78, 'млн.шт.', 'mln.dona'),
 ( gen_random_uuid(), 79, 'набор', 'to‘plam'),
 ( gen_random_uuid(), 80, 'объект', 'obyekt'),
 ( gen_random_uuid(), 81, 'проба', 'proba'),
 ( gen_random_uuid(), 82, 'пучок', 'puchok'),
 ( gen_random_uuid(), 83, 'тыс.т.', 'ming t.'),
 ( gen_random_uuid(), 84, 'тыс.шт.', 'ming dona'),
 ( gen_random_uuid(), 85, 'услуга', 'xizmat'),
 ( gen_random_uuid(), 86, 'шлиф', 'shlif'),
 ( gen_random_uuid(), 87, 'банка', 'banka'),
 ( gen_random_uuid(), 88, 'пэт', 'pet'),
 ( gen_random_uuid(), 89, 'WGRP', 'WGRP'),
 ( gen_random_uuid(), 90, 'копия', 'nusxa'),
 ( gen_random_uuid(), 91, 'человек', 'odam'),
 ( gen_random_uuid(), 92, 'выход', 'chiqish');
